# Generated by Django 2.2.2 on 2020-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('order_type', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=255)),
            ],
        ),
    ]
