# Generated by Django 2.2.2 on 2020-06-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_type',
            field=models.CharField(choices=[('BHARTIARTL.NS', 'BHARTIARTL.NS'), ('ASHOKLEY.NS', 'ASHOKLEY.NS'), ('AUROPHARMA.NS', 'AUROPHARMA.NS'), ('RELIANCE.NS', 'RELIANCE.NS'), ('TCS.NS', 'TCS.NS'), ('BAJFINANCE.NS', 'BAJFINANCE.NS'), ('HINDUNILVR.NS', 'HINDUNILVR.NS'), ('IBN', 'IBN'), ('LT.BO', 'LT.BO'), ('ITC.BO', 'ITC.BO')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Bid', 'Bid'), ('Sell', 'Sell')], max_length=255),
        ),
    ]
