# Generated by Django 2.2.2 on 2020-06-24 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
