# Generated by Django 2.2.2 on 2020-06-24 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_order_placed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
